export const enemyAbilityList = [
  {
    name: 'ヌシ',
    id: 'boss',
    list: [
      {
        name: '単体攻撃',
        group: 'ヌシ',
        type: '攻撃',
        recoil: '0',
        specialty: '任意',
        target: '単体',
        effect:
          '指定特技の判定に成功すると、対象に2D6点のダメージを与える。この攻撃の命中判定の達成値にプラス2の修正がつく。',
      },
      {
        name: '全体攻撃',
        group: 'ヌシ',
        type: '攻撃',
        recoil: '0',
        specialty: '任意',
        target: '全体',
        effect:
          '指定特技の判定に成功すると、対象に1点のダメージを与える。連続した手番には使用できない。',
      },
      {
        name: '範囲攻撃',
        group: 'ヌシ',
        type: '攻撃',
        recoil: '0',
        specialty: '任意',
        target: '二体',
        effect: '指定特技の判定に成功すると、対象に3点のダメージを与える。',
      },
      {
        name: '恒常性',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '変調を受けているとき、自分の手番の前に1D6を振る。その出目が受けている変調の数以下ならば、任意の変調を１つ解除できる。『無力化状態』の時にはラウンドの最後に1D6を振り、[受けている変調の数＋1]以下の出目が出た場合『無力化状態』を回復する。',
      },
      {
        name: '習性',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          'その戦闘中に条件を満たした時、追加行動を得る。条件はセッション前にGMが決定する。（例：自分が死亡判定を行った時、【体力】が0になった時、床にダイスが落ちた時など）',
      },
      {
        name: 'コア',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '死亡判定のダイスを１つ増やす。弱点として「身体部位」を１つ指定する。弱点に部位ダメージが入るとこの効果は失われる。',
      },
      {
        name: 'とりまき',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '-',
        effect:
          'ヌシ以外のエネミーと同時に登場できる。【とりまき】によって登場するエネミーの合計レベルは[ヌシのレベル×2]、数は[ヌシのレベル]体までとなる。',
      },
      {
        name: '追加体力',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '【体力】を[自身のレベル×3]点増加させる。',
      },
      {
        name: '追加気力',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '【気力】を[自身のレベル×3]点増加させる。',
      },
      {
        name: '絶対成功',
        group: 'ヌシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '達成値が対象値にとどかない場合でも命中判定に成功する。その場合、相手の回避判定には[(対象値-達成値）×2]点の修正がつく。',
      },
    ],
  },
  {
    name: 'ムシ',
    id: 'insect',
    list: [
      {
        name: '大アゴ',
        group: 'ムシ',
        type: '攻撃',
        recoil: '0',
        specialty: '《噛む》',
        target: '単体',
        effect: '指定特技の判定に成功すると対象に3点のダメージを与える。',
      },
      {
        name: '毒針',
        group: 'ムシ',
        type: '攻撃',
        recoil: '3',
        specialty: '《刺す》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象に1点のダメージを与える。その結果1点でも【HP】が減った場合、対象に『毒』の変調を与える。',
      },
      {
        name: '外骨格',
        group: 'ムシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: 'あなたが受けるダメージを1点軽減する。',
      },
      {
        name: '飛行',
        group: 'ムシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '回避判定の達成値にプラス1の修正がつく。',
      },
      {
        name: '大鎌',
        group: 'ムシ',
        type: '補助',
        recoil: '5',
        specialty: '-',
        target: '-',
        effect: '命中判定に組み合わせて使用する。ダメージを1D6点増加させる。',
      },
      {
        name: '触手',
        group: 'ムシ',
        type: '攻撃',
        recoil: '2',
        specialty: '《操作》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると、対象に1点のダメージを与える。さらに、対象はラウンド終了まで割込みタイプと補助タイプのアビリティが使用不可になる。',
      },
    ],
  },
  {
    name: 'ケモノ',
    id: 'beast',
    list: [
      {
        name: '体当たり',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '0',
        specialty: '自由',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象に1点のダメージを与える。この時命中判定の達成値にプラス2の修正がつく。',
      },
      {
        name: '噛みつき',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '0',
        specialty: '《噛む》',
        target: '単体',
        effect: '指定特技の判定に成功すると対象に2点のダメージを与える。',
      },
      {
        name: '突撃',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '3',
        specialty: '《走る》',
        target: '全体',
        effect:
          '指定特技の判定に成功すると、3点のダメージを与える。ただし、対象は1D6を振って奇数がでた場合、攻撃の対象から外れる。',
      },
      {
        name: '鋭角',
        group: 'ケモノ',
        type: '補助',
        recoil: '1',
        specialty: '-',
        target: '-',
        effect: '命中判定に組み合わせて使用する。ダメージを1点増加させる。',
      },
      {
        name: '牙',
        group: 'ケモノ',
        type: '補助',
        recoil: '2',
        specialty: '-',
        target: '-',
        effect: '命中判定に組み合わせて使用する。ダメージを2点増加させる。',
      },
      {
        name: '咆哮',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '2',
        specialty: '《叫ぶ》',
        target: '全体',
        effect: '指定特技の判定に成功すると、対象に『麻痺』の変調を与える。',
      },
    ],
  },
  {
    name: 'ミュータント',
    id: 'mutant',
    list: [
      {
        name: '撹乱音波',
        group: 'ミュータント',
        type: '補助',
        recoil: '1',
        specialty: '-',
        target: '-',
        effect:
          '命中判定に組み合わせて使用する。攻撃が命中した相手は、次のラウンドの終了まで全ての行為判定の達成値にマイナス１の修正がつく。',
      },
      {
        name: '鋼鱗',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '自身が受けるダメージを2点軽減する。ただしその際に気力が1点減少する。',
      },
      {
        name: 'ドリル',
        group: 'ミュータント',
        type: '補助',
        recoil: '3',
        specialty: '-',
        target: '-',
        effect:
          '命中判定に組み合わせて使用する。ダメージを2点増加させ、対象に『重傷』の変調を与える。',
      },
      {
        name: '火炎放射',
        group: 'ミュータント',
        type: '攻撃',
        recoil: '2',
        specialty: '《呼吸器》',
        target: '全体',
        effect: '指定特技の判定に成功すると、敵全体に『炎上』の変調を与える。',
      },
      {
        name: '冷気',
        group: 'ミュータント',
        type: '補助',
        recoil: '1',
        specialty: '-',
        target: '-',
        effect:
          '命中判定に組み合わせて使用する。対象の特技リストから「腕部」分野の特技を１つランダムに使用不能にする。この効果は重複する。',
      },
      {
        name: '腐敗',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '-',
        effect:
          'ラウンド終了時に全体の【気力】を1点減少させる。【腐敗】のアビリティを習得している対象には効果を発揮しない。',
      },
    ],
  },
  {
    name: 'その他',
    id: 'other',
    list: [
      {
        name: '死亡判定',
        group: 'その他',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '【体力】が０になっても死亡せず、死亡判定が発生する。',
      },
    ],
  },
];

export const strangeFieldsEnemyAbilityList = [
  {
    name: 'ムシ',
    id: 'insect',
    list: [
      {
        name: '麻痺毒',
        group: 'ムシ',
        type: '補助',
        recoil: '2',
        specialty: '-',
        target: '-',
        effect:
          '命中判定に組み合わせて使用する。対象に『麻痺』の変調を与える。',
      },
      {
        name: '蜘蛛の巣',
        group: 'ムシ',
        type: '支援',
        recoil: '2',
        specialty: '《罠》',
        target: '全体',
        effect:
          '指定特技の判定に成功すると、戦闘中回避判定に失敗した対象に『捕縛』の変調を与える。この効果は支援行動で、《斬る》の判定に成功するか、「たいまつ」を消費するまで持続する。',
      },
      {
        name: '甲羅',
        group: 'ムシ',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          'あなたはダメージを受ける時、先にそのダメージの命中部位を決める。胴部分野の《身体部位》に攻撃が命中した場合、そのダメージを3点軽減する。',
      },
      {
        name: '吸血',
        group: 'ムシ',
        type: '攻撃',
        recoil: '3',
        specialty: '《消化器》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象にダメージを1d6点与え、自分の【体力】を同じだけ回復する。',
      },
      {
        name: '大鋏',
        group: 'ムシ',
        type: '攻撃',
        recoil: '5',
        specialty: '《掴む》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象にダメージを1d6点与える。ダメージダイスで１つでも6の出目がでた場合、攻撃後、対象の【体力】が1以上でも部位ダメージとなる。',
      },
      {
        name: '強酸',
        group: 'ムシ',
        type: '攻撃',
        recoil: '5',
        specialty: '《掴む》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると、1点のダメージを与える。このダメージは軽減されない。さらに対象の装備1つの効果を1点下げる。キャンプに【工房】があれば、キャンプに戻った時点で装備を元の状態に戻すことができる。',
      },
    ],
  },
  {
    name: 'ケモノ',
    id: 'beast',
    list: [
      {
        name: '翼',
        group: 'ケモノ',
        type: '支援',
        recoil: '3',
        specialty: '《罠》',
        target: '全体',
        effect:
          '指定特技の判定に成功すると、戦場をランダムに変更することができる。最初に1d6を振って奇数なら戦場表A、偶数なら戦場表Bを使う。',
      },
      {
        name: 'おおぶり',
        group: 'ケモノ',
        type: '補助',
        recoil: '3',
        specialty: '-',
        target: '-',
        effect:
          '命中判定に組み合わせて使用する。命中判定にマイナス1の修正がつき、ダメージが3点増加する。',
      },
      {
        name: '切り裂き',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '3',
        specialty: '《斬る》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象にダメージを2点与え、1点でもダメージが通れば『重傷』の変調を与える。',
      },
      {
        name: '尾の鞭',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '6',
        specialty: '《振る》',
        target: '本文',
        effect:
          '指定特技の判定に成功すると2体の対象にダメージを2点与えるか、単体に2点のダメージを2回与える。',
      },
      {
        name: '飛びかかり',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '4',
        specialty: '《跳ぶ》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると対象にダメージを4点と、『転倒』の変調を与える。',
      },
      {
        name: '誘い込み',
        group: 'ケモノ',
        type: '攻撃',
        recoil: '3',
        specialty: '《追い込む》',
        target: '単体',
        effect:
          '指定特技の判定に成功すると、目標の特技リストから「腕部」分野の特技を１つランダムに使用不能にする。この効果は重複する。',
      },
    ],
  },
  {
    name: 'ミュータント',
    id: 'mutant',
    list: [
      {
        name: '骨の体',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '指定特技が《斬る》《刺す》の攻撃のダメージを2点軽減する。',
      },
      {
        name: '肉の鎧',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '指定特技が《殴る》の攻撃のダメージを2点軽減する。',
      },
      {
        name: '樹の体',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          'ラウンドの終わりに1D6点【体力】が回復する。自身が受けた【炎上】により減少する値が2倍になる。',
      },
      {
        name: '不定形',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '命中部位決定表の7が出た時、自身の任意の部位を選んでよい。',
      },
      {
        name: '機械の体',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '『毒』の変調を無効化する。【充電】の必要な装備を装備している場合、常に充電されているものとして扱う。',
      },
      {
        name: 'つぎはぎ',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          '回避判定を行う代わりに任意の部位に部位ダメージをうけることで回避判定に成功したことにできる。また、生死判定にプラス1の修正がつく。',
      },
      {
        name: '追加肢',
        group: 'ミュータント',
        type: '攻撃',
        recoil: '0',
        specialty: '自由',
        target: '単体',
        effect:
          '指定特技の判定に成功すると、組み合わせた補助アビリティの効果が発動する。このアビリティと組み合わせた補助アビリティの反動は1少ないものとして扱う。',
      },
      {
        name: '追加目',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '命中判定にプラス1の修正がつく。',
      },
      {
        name: '電撃',
        group: 'ミュータント',
        type: '攻撃',
        recoil: '2',
        specialty: '自由',
        target: '単体',
        effect:
          '攻撃が成功すると目標に3点のダメージを与えさらに『麻痺』の変調を与える。',
      },
      {
        name: '硬質化',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect:
          'ダメージを受けるとラウンド終了まで、次以降に受けるダメージを2点軽減する。この修正は累積する。',
      },
      {
        name: '鉄塊',
        group: 'ミュータント',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '自身',
        effect: '追加行動で行う攻撃のダメージにプラス4の修正がつく。',
      },
      {
        name: '悪臭',
        group: 'ミュータント',
        type: '攻撃',
        recoil: '3',
        specialty: '《消化器》',
        target: '全体',
        effect: '指定特技の判定に成功すると、ランダムに変調を1つ与える。',
      },
    ],
  },
  {
    name: 'その他',
    id: 'other',
    list: [
      {
        name: '無反動',
        group: 'その他',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '-',
        effect:
          '習得している【アビリティ】を１つ選ぶ。その反動を0にする。ヌシは取得できない。',
      },
      {
        name: '装備',
        group: 'その他',
        type: '常駐',
        recoil: '-',
        specialty: '-',
        target: '-',
        effect: '装備を１つ選ぶ。それを所持していることになる。',
      },
    ],
  },
];
