export const items = [
  {
    name: 'ジャーキー',
    j: 1,
    weight: 1,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '食料',
    effect: '1日分の食料。【気力】が1点増加する。通貨単位J。',
  },
  {
    name: '缶詰',
    j: 10,
    weight: 1,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '食料',
    effect:
      '缶詰1つ。文明の味。【気力】が「【精神力】」点増加する。通貨単位10J=1C。',
  },
  {
    name: 'ベルトポーチ',
    j: 3,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量4まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。',
  },
  {
    name: 'リュックサック',
    j: 5,
    weight: 2,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量10まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。',
  },
  {
    name: '大きなリュック',
    j: 10,
    weight: 3,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量20まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。',
  },
  {
    name: '肩掛けカバン',
    j: 6,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量4まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。戦闘中でも袋の中のアイテムを使用できる。',
  },
  {
    name: '手提げかばん',
    j: 6,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量5まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。戦闘中でも袋の中のアイテムを使用できる。',
  },
  {
    name: 'トランクケース',
    j: 7,
    weight: 3,
    type: '装備',
    area: '両手',
    specialty: '《殴る》',
    target: '単体',
    trait: '袋、武器、白兵',
    effect:
      '攻撃力3。総重量5まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。',
  },
  {
    name: '棍棒',
    j: 1,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力1。',
  },
  {
    name: 'バール',
    j: 4,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力2。',
  },
  {
    name: '槍',
    j: 4,
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《刺す》',
    target: '単体',
    trait: '武器、白兵、収納不可',
    effect: '攻撃力3。',
  },
  {
    name: 'ナタ',
    j: 6,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力3。',
  },
  {
    name: 'ハンマー',
    j: 6,
    weight: 5,
    type: '装備',
    area: '両手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力4。硬くて長くて重たいの。',
  },
  {
    name: '農具',
    j: 15,
    weight: 6,
    type: '装備',
    area: '両手',
    specialty: '《振る》',
    target: '単体',
    trait: '武器、白兵、収納不可',
    effect: '攻撃力5。死神が振るうような鎌、或いは、大地を耕す鍬。',
  },
  {
    name: 'ダガーナイフ',
    j: 6,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力1。先制判定の達成値にプラス1の修正がつく。この武器は割込みのタイミングで装備できる。取り回しやすい本格的なナイフ。',
  },
  {
    name: 'カタナ',
    j: 15,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力4。命中判定でスペシャルを振った場合、攻撃力にプラス1D6する。',
  },

  {
    name: 'ほうちょう',
    j: 3,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力1。この武器は割込みのタイミングで装備できる。この武器は破壊して死亡判定をキャンセルできない。',
  },

  {
    name: '手斧',
    j: 6,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力2。《投げる》を使って判定した場合、手元から失われる。支援行動で回収できる。',
  },
  {
    name: '杭',
    j: 7,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《刺す》《跳ぶ》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力2。くい。突き刺す武器。',
  },

  {
    name: '斧',
    j: 8,
    weight: 4,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《振る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力3。',
  },
  {
    name: '鎖',
    j: 8,
    weight: 3,
    type: '装備',
    area: '片手',
    specialty: '《振る》《捕らえる》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力3。',
  },
  {
    name: 'シャベル',
    j: 8,
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵、判定強化',
    effect: '攻撃力3。',
  },
  {
    name: 'ツルハシ',
    j: 9,
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《刺す》《振る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力4。',
  },
  {
    name: '百科事典',
    j: 9,
    weight: 3,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力2。所持していると《雑学》の判定の達成値にプラス1の修正がつく。',
  },
  {
    name: 'スリング',
    j: 3,
    weight: 1,
    type: '装備',
    area: '両手',
    specialty: '《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力2。投石器。弾にする石は何処でも手に入るため明記不要。石以外も投げることができる。装備している間、回避判定にプラス1の修正がつく。',
  },
  {
    name: 'ボウガン',
    j: 8,
    weight: 3,
    type: '装備',
    area: '両手',
    specialty: '《撃つ》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力3。矢が必要。装備している間、回避判定にプラス2の修正がつく。',
  },
  {
    name: 'スタンガン',
    j: 8,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵、充電、使用回数：1',
    effect:
      '攻撃力2。この武器によるダメージは軽減されない。さらに、『麻痺』の変調を与える。',
  },
  {
    name: '剥ぎ取りナイフ',
    j: 9,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力2。ドロップ表の結果にプラス1の修正がつく。',
  },
  {
    name: '追打茨のムチ',
    j: 12,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《振る》《捕らえる》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力3。変調を持つ相手へのダメージをプラス1。変調が2つなら+3、4つ以上で+6。',
  },
  {
    name: '血染桜のシャベル',
    j: 12,
    weight: 3,
    type: '装備',
    area: '片手',
    specialty: '《殴る》《斬る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力3。自身の体力が1以下の時、攻撃力プラス3。',
  },
  {
    name: '疾風竹の槍',
    j: 13,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《刺す》《跳ぶ》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力2。先攻での攻撃時、命中判定にプラス1と攻撃力にプラス2の修正がつく。',
  },

  {
    name: 'なべぶた',
    j: 1,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵、防具',
    effect: '攻撃力0。回避判定の達成値にプラス1の修正がつく。',
  },
  {
    name: 'なべ',
    j: 10,
    weight: 2,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '防具',
    effect:
      '頭部分野の《身体部位》への部位ダメージをキャンセルすることができる。そうした場合、このアイテムを破壊する。',
  },
  {
    name: 'レザー',
    j: 10,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '防具',
    effect:
      '胴部分野の《身体部位》への部位ダメージをキャンセルすることができる。そうした場合、このアイテムを破壊する。',
  },
  {
    name: 'ポケットジャケット',
    j: 12,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'ポケットのたくさんついたジャケット。所持限界プラス1',
  },
  {
    name: '籠手',
    j: 10,
    weight: 2,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '防具',
    effect:
      '腕部分野の《身体部位》への部位ダメージをキャンセルすることができる。そうした場合、このアイテムを破壊する。',
  },
  {
    name: '安全ブーツ',
    j: 10,
    weight: 3,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '防具',
    effect:
      '脚部分野の《身体部位》への部位ダメージをキャンセルすることができる。そうした場合、このアイテムを破壊する。',
  },
  {
    name: '嗜好品',
    j: 3,
    weight: 0,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: 'おやつやタバコなど。【気力】を2点増加させる。',
  },
  {
    name: 'ライト',
    j: 3,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '-',
    target: '自身',
    trait: '充電',
    effect:
      '《探索》の達成値にプラス1の修正がつく。明るく照らす。暗闇のペナルティを打ち消す。',
  },
  {
    name: 'バッテリー',
    j: 2,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: 'あなたが装備しているか所持しているアイテム1つを「充電」できる。',
  },
  {
    name: 'トランシーバー',
    j: 8,
    weight: 1,
    type: '支援',
    area: '-',
    specialty: '《機械》',
    target: '自身',
    trait: '充電',
    effect: 'キャンプの仲間と通信し、【気力】を2点増加させる。',
  },
  {
    name: '携帯ラジオ',
    j: 8,
    weight: 1,
    type: '支援',
    area: '-',
    specialty: '《操作》',
    target: '全体',
    trait: '充電',
    effect: '探索フェイズに使用可能。全員の【気力】を1D3点増加させる。',
  },
  {
    name: '矢',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品、使用回数：10',
    effect:
      'ボウガンの矢。これを所持していないとボウガンの効果をうけることができない。ボウガンで命中判定を行うごとに1消費する。',
  },
  {
    name: '矢筒',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '名前に『矢』のつくアイテムを3束（使用回数30回分）まで入れることができる。袋の中のアイテムの重量は所持限界から無視する。戦闘中でも袋の中のアイテムを使用できる。',
  },
  {
    name: '胡椒玉',
    j: 5,
    weight: 0,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect:
      'スリングで投げることができる。攻撃の対象に『麻痺』の変調を与える。',
  },
  {
    name: 'コカの葉',
    j: 2,
    weight: 0,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: '【体力】を2点増加させる。',
  },
  {
    name: 'なんこう',
    j: 3,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: '変調を１つ回復する。',
  },
  {
    name: '鎮痛剤',
    j: 6,
    weight: 0,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: '【体力】を3点増加させる。変調を1つ回復する。',
  },
  {
    name: '手書きのメモ',
    j: 5,
    weight: 0,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '単体',
    trait: '消耗品',
    effect: '対象に『暴露』の変調を与える。',
  },
  {
    name: 'ばんそうこう',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品',
    effect: '【応急手当て】【ちちんぷいぷい】の効果プラス1。',
  },
  {
    name: 'ペット',
    j: 10,
    weight: 0,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '食料',
    effect: '【気力】を1D3点増加させる。',
  },
  {
    name: 'ロープ',
    j: 1,
    weight: 2,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '',
    effect: '丈夫なロープ。使い方次第で休憩しやすくなったり障害の突破に。',
  },
  {
    name: 'たいまつ',
    j: 1,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '-',
    target: '-',
    trait: '消耗品',
    effect:
      '火をつけるには火付け道具が必要、戦闘中の点火は支援行動。効果は1サイクル。暗闇のペナルティを打ち消したり蜘蛛の巣を燃やしたり。',
  },
  {
    name: '火付け道具',
    j: 2,
    weight: 0,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '',
    effect:
      'マッチやライター、火打ち石とほくちのセットなどのこと。焚き火があれば休憩しやすくなる。',
  },
  {
    name: '毛布',
    j: 1,
    weight: 2,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '',
    effect: '軽くて丈夫な毛布。寒い日の休憩には必須。',
  },
  {
    name: '寝袋',
    j: 5,
    weight: 3,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '',
    effect: '休憩をした時に増加する【気力】プラス1。',
  },
  {
    name: 'ポリタンク',
    j: 5,
    weight: 3,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '',
    effect:
      'キャンプや水場で水を補充できる。水が補充されている場合、いつでもリミットの増加を試みることができる。一度使うと水はなくなる。空なら重量3、水を満タンにすると重量は8となる。',
  },
  {
    name: '釣竿',
    j: 7,
    weight: 2,
    type: '支援',
    area: '-',
    specialty: '《待つ》',
    target: '-',
    trait: '',
    effect:
      '川や池を見つけた時に使用出来る。指定特技の判定に成功すると1Jを得る。',
  },
  {
    name: 'なぞの葉',
    j: 0,
    weight: 0,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '購入不可、消耗品',
    effect:
      '使用するときに1D6を振る。出目が偶数の場合、【体力】が2点増加する。奇数の場合、2点のダメージを受ける。',
  },
  {
    name: '生肉',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可、食料',
    effect: 'お肉にくにく。',
  },
  {
    name: '硬い殻',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '武器・防具の材料に使える硬い殻',
  },
  {
    name: '硬い羽',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '透き通った硬い羽。武器防具以外に窓ガラスの修理にも。',
  },
  {
    name: '毒針',
    j: 2,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '毒は薬にも。針は武器や工具に使用される。',
  },
  {
    name: '毛皮',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: 'もふもふ',
  },
];
export const strangeFieldsItemList = [
  {
    name: '行商人の背負い袋',
    j: 40,
    weight: 6,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '袋',
    effect:
      '総重量40まで袋の中にアイテムを入れることができる。袋の中のアイテムの重量は所持限界から無視する。回避判定にマイナス1の修正がつく。商人御用達の特大の背負い袋。',
  },
  {
    name: '猟銃',
    j: 30,
    weight: 6,
    type: '装備',
    area: '両手',
    specialty: '《撃つ》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力5。防御力無視ダメージを与える。弾が必要。装備している間、回避判定にプラス2の修正がつく。',
  },
  {
    name: '弾',
    j: 5,
    weight: 0,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品、使用回数：10',
    effect:
      'これを所持していないと猟銃の効果をうけることができない。猟銃で命中判定を行うごとに1消費する。',
  },
  {
    name: '弓',
    j: 5,
    weight: 3,
    type: '装備',
    area: '両手',
    specialty: '《撃つ》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力3。矢が必要。装備している間、回避判定にプラス2の修正がつく。ハンター専用。',
  },
  {
    name: 'ダーツ',
    j: 12,
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力1。割り込みのタイミングで攻撃することが可能。手番は消費しない。投げた後、手元から失われる。戦闘終了後に回収できる。バランスの取れた投射用の短刀。',
  },
  {
    name: '大盾',
    j: 10,
    weight: 6,
    type: '装備',
    area: '両手',
    specialty: '《走る》',
    target: '単体',
    trait: '武器、白兵、防具、収納不可',
    effect:
      '攻撃力3。命中判定の達成値にマイナス2の修正がつく。装備している間、回避判定にプラス2の修正がつく。',
  },
  {
    name: 'おしゃれな服',
    j: 1,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '-',
    trait: '防具',
    effect: 'こんな世界でも身だしなみを大切に。',
  },
  {
    name: 'アクセサリ',
    j: 2,
    weight: 1,
    type: '装備',
    area: '任意',
    specialty: '-',
    target: '-',
    trait: '防具',
    effect: '任意の部位に装備することができる。お気に入りの逸品。',
  },
  {
    name: '魚肉',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可、食料',
    effect: '魚肉。足が早いので、すぐに干物にすべし。',
  },
  {
    name: '硬い鱗',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '固くて大きな鱗。齢を経たサカナほど刻まれる年輪は多くなる',
  },
  {
    name: '虹色の鱗',
    j: 1,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '透明感のある虹色の鱗。宝石代わりに装飾品に使われる。',
  },
];
export const dragonPlainItemList = [
  {
    name: '抗生物質',
    j: 10,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect: '変調を全て回復する',
  },
  {
    name: '森の恵み',
    j: 15,
    weight: 2,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '単体',
    trait: '消耗品',
    effect: '対象の【体力】・【気力】を5点増加する',
  },
  {
    name: '奇跡の雫',
    j: 20,
    weight: 2,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '単体',
    trait: '消耗品',
    effect: '対象の部位ダメージを1つ回復し、変調を全て回復する',
  },
  {
    name: '銀の矢',
    j: 5,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品、使用回数:10',
    effect:
      'ボウガン/弓の矢。アビリティ【腐敗】を持つ敵に対して攻撃が成功した場合、ダメージをプラス3し、さらに気力を2点減らす',
  },
  {
    name: '毒の矢',
    j: 5,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品、使用回数:10、アビリティ強化',
    effect:
      'ハンター専用。ボウガン/弓の矢。攻撃対象の【体力】が減少したとき、『毒』の変調を与える効果を追加する。また、【毒矢】のアビリティ使用時に消費すると、ダメージをプラス2し反動を1減らすことができる',
  },
  {
    name: 'ダウジングツール',
    j: 2,
    weight: 1,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品',
    effect:
      'ニューエイジ・オガミヤ専用。探索フェイズで[オブジェクトへの接触]を2回行う。また、この時に振る判定や表を1回だけ振りなおすことができる。',
  },
  {
    name: '爆竹玉',
    j: 5,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品',
    effect:
      'スリングで投げることができる。攻撃の対象に5点の防御無視ダメージを与える。',
  },
  {
    name: '臭い玉',
    j: 5,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '消耗品',
    effect:
      'スリングで投げることができる。攻撃の対象に追加で2点の気力ダメージを与える。',
  },
  {
    name: 'けむりだま',
    j: 3,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品',
    effect:
      '＜ヌシ＞以外からの戦闘からの逃走判定の直前に使用する。逃走判定の達成値にプラス4の修正がつく',
  },
  {
    name: 'しもふりにく',
    j: 4,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '食料、消耗品、アビリティ強化',
    effect:
      'カイヌシの【群れ攻撃】で消費する食料2つをこのアイテム1つの消費でまかなうことができる。さらに、攻撃の対象を「全体」に変更することができる。',
  },
  {
    name: 'わらにんぎょう',
    j: 5,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品、アビリティ強化',
    effect:
      'オガミヤの【呪術】の判定に成功したときに使用する。【呪術】で与えた『毒』で減少する【体力】を[1d6+【呪術】使用者の部位ダメージ数]点に変更する。',
  },
  {
    name: '結界符',
    j: 5,
    weight: 1,
    type: '割込み',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品、アビリティ強化',
    effect:
      'オガミヤ専用。オガミヤの【結界】成功時に割込んで使用できる。あなたは未行動状態となる。',
  },
  {
    name: 'いくさ化粧',
    j: 5,
    weight: 2,
    type: '支援',
    area: '-',
    specialty: '-',
    target: '自身',
    trait: '消耗品、アビリティ強化',
    effect:
      'ヤセイジの【抜刀牙】で与えるダメージが[2d6]点となり、消費する気力も同じ点数となる。また、攻撃後、敵の体力が0以下の場合、【抜刀牙】で消費する気力は0点となり、【体力】と【気力】が1点増加する。この効果はセッション中持続する。',
  },

  {
    name: '盾',
    j: 20,
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力1。回避判定の達成値にプラス1の修正がつく。',
  },
  {
    name: '銀の首飾り',
    j: 5,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '＜フィールド＞に入った時に【体力】が3点増加する。',
  },
  {
    name: 'ゴーグル',
    j: 10,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: 'アビリティ強化',
    effect:
      'ハンターの【アビリティ】を使用する直前に、追加で1点の気力を払うことができる。そうした場合、達成値にプラス1の修正がつく。',
  },
  {
    name: 'モノクル',
    j: 10,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《見つける》が指定特技の判定にプラス1の修正がつく。',
  },
  {
    name: '浄化の聖印',
    j: 15,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'アビリティ【腐敗】【悪臭】を無効化する。',
  },
  {
    name: 'リボン',
    j: 100,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'あらゆる変調から身を守る。',
  },

  {
    name: '風見鶏のスカーフ',
    j: 20,
    weight: 1,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '先制判定の達成値にプラス1の修正がつく。',
  },
  {
    name: '赤い服',
    j: 2,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect:
      '牛/虎の姿の敵があなただけを狙ってくる。その敵を倒したとき、体力・気力が3点増加する。',
  },
  {
    name: 'サバイバルベスト',
    j: 15,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '【生命力】をプラス1する。',
  },
  {
    name: '快適な下着',
    j: 10,
    weight: 1,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '【精神力】をプラス1する。',
  },
  {
    name: 'もふもふコート',
    j: 10,
    weight: 4,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '環境効果『極寒』の影響を受けない。',
  },
  {
    name: 'トラップツール',
    j: 15,
    weight: 4,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: 'アビリティ強化、判定強化',
    effect:
      'ハンターの【影牢】のダメージ量を[対象が受けている変調×2]点に変更する。《罠》が指定特技の判定にプラス1の修正がつく。',
  },
  {
    name: 'アイドル衣装',
    j: 15,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: 'アビリティ強化',
    effect:
      'アイドルの【応援歌】【熱狂のビート】が指定特技の判定に失敗しても効果を発揮するようになり、判定に成功した場合、あなたは未行動状態になる。',
  },

  {
    name: 'パワーグラブ',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《掴む》が指定特技の判定にプラス1の修正がつく。',
  },
  {
    name: '投手の手袋',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《投げる》が指定特技の判定にプラス1の修正がつく。',
  },
  {
    name: 'ロンググローブ',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'アビリティ【冷気】の影響を受けない。',
  },

  {
    name: '水かき',
    j: 5,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '水中で行う《泳ぐ》が指定特技の判定にプラス2の修正がつく。',
  },
  {
    name: '俊足スニーカー',
    j: 15,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect:
      '《走る》が指定特技の判定にプラス1の修正がつく。探索フェイズ時、障害の突破判定でスペシャルを出すと、行動済にならず続けて行動できる。',
  },
  {
    name: 'フィットシューズ',
    j: 20,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect:
      '《バランス》が指定特技の判定にプラス1の修正がつく。『瓦礫』などの足場ペナルティ無効。アビリティ【地震】無効。',
  },
  {
    name: '忍者の足袋',
    j: 20,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《歩く》《隠れる》が指定特技の判定にプラス1の修正がつく。',
  },
  {
    name: 'ペガサスの靴',
    j: 30,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《走る》《跳ぶ》《踏む》が指定特技の判定にプラス1の修正がつく。',
  },

  {
    name: '星の欠片:赤',
    j: 10,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect:
      '金平糖の形をしている赤色の宝石。武器の＜ダメージ強化＞に使用できる。',
  },
  {
    name: '星の欠片:緑',
    j: 10,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '金平糖の形をしている緑色の宝石。武器の＜命中強化＞に使用できる。',
  },
  {
    name: '星の欠片:青',
    j: 10,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect:
      '金平糖の形をしている青色の宝石。防具の＜ダメージ軽減＞に使用できる。',
  },
  {
    name: '星の欠片:黄',
    j: 10,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect:
      '金平糖の形をしている黄色の宝石。防具の＜回避力強化＞に使用できる。',
  },
  {
    name: '星の欠片:白',
    j: 10,
    weight: 1,
    type: '道具',
    area: '-',
    specialty: '-',
    target: '-',
    trait: '購入不可',
    effect: '三日月の形をしている白色の宝石。防具の＜高品質化＞に使用できる。',
  },
];
export const dragonPlainGreaterItemList = [
  {
    name: '☾ほうちょう',
    j: '3',
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力1。この武器は割込みのタイミングで装備できる。《料理》が指定特技の判定の達成値+2。',
  },
  {
    name: '☾ナタ',
    j: '6',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力3。命中判定の達成値+2。',
  },
  {
    name: '☾剥ぎ取りナイフ',
    j: '9',
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力2。ドロップ表の結果にプラス2の修正がつく。',
  },
  {
    name: '☾カタナ',
    j: '15',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力4。命中判定でスペシャルを振った場合、攻撃力にプラス2D6する。',
  },
  {
    name: '☾槍',
    j: '4',
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《刺す》',
    target: '単体',
    trait: '武器、白兵、収納不可',
    effect: '攻撃力3。命中判定の達成値+1。回避判定の達成値+1。',
  },
  {
    name: '☾棍棒',
    j: '1',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力1。命中判定の達成値+1。使用する【アビリティ】の反動-1(最低0)。',
  },
  {
    name: '☾バール',
    j: '4',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力3。攻撃が命中した場合、対象の、ダメージを軽減する【アビリティ】を1ラウンドの間無効化する。',
  },
  {
    name: '☾ハンマー',
    j: '6',
    weight: 5,
    type: '装備',
    area: '両手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力5。命中判定の達成値+2。硬くて長くて重たいの。',
  },
  {
    name: '☾スリング',
    j: '3',
    weight: 1,
    type: '装備',
    area: '両手',
    specialty: '《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力2。命中判定の達成値+1。投石器。弾にする石は何処でも手に入るため明記不要。石以外も投げることができる。装備している間、回避判定にプラス1の修正がつく。',
  },
  {
    name: '☾弓',
    j: '5',
    weight: 3,
    type: '装備',
    area: '両手',
    specialty: '《撃つ》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力4。命中判定の達成値+1。矢が必要。装備している間、回避判定にプラス2の修正がつく。ハンター専用。',
  },
  {
    name: '☾ダーツ',
    j: '12',
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect:
      '攻撃力1。割り込みのタイミングで攻撃することが可能。この攻撃によるダメージは軽減されない。手番は消費しない。投げた後、手元から失われる。戦闘終了後に回収できる。バランスの取れた投射用の短刀。',
  },
  {
    name: '☾手斧',
    j: '6',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《投げる》',
    target: '単体',
    trait: '武器、射撃',
    effect: '攻撃力3。',
  },
  {
    name: '☾ダガーナイフ',
    j: '6',
    weight: 1,
    type: '装備',
    area: '片手',
    specialty: '《刺す》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力2。命中判定の達成値+1。先制判定の達成値にプラス1の修正がつく。この武器は割込みのタイミングで装備できる。取り回しやすい本格的なナイフ。',
  },
  {
    name: '☾農具',
    j: '15',
    weight: 6,
    type: '装備',
    area: '両手',
    specialty: '《振る》',
    target: '3体',
    trait: '武器、白兵、収納不可',
    effect:
      '攻撃力5。【なぎ払い】の対象を+2する。死神が振るうような鎌、或いは、大地を耕す鍬。',
  },
  {
    name: '☾大盾',
    j: '10',
    weight: 6,
    type: '装備',
    area: '両手',
    specialty: '《走る》',
    target: '単体',
    trait: '武器、白兵、防具、収納不可',
    effect: '攻撃力3。装備している間、回避判定にプラス2の修正がつく。',
  },
  {
    name: '☾ツルハシ',
    j: '9',
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《刺す》《振る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力4。この攻撃によるダメージは軽減されない。',
  },
  {
    name: '☾斧',
    j: '7',
    weight: 4,
    type: '装備',
    area: '片手',
    specialty: '《斬る》《振る》',
    target: '単体',
    trait: '武器、白兵',
    effect: '攻撃力5。',
  },
  {
    name: '☾鎖',
    j: '9',
    weight: 3,
    type: '装備',
    area: '片手',
    specialty: '《振る》《捕らえる》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力3。変調を持つ相手には攻撃力+1。変調が2つ以上なら攻撃力+3。変調4つ以上なら+6。',
  },
  {
    name: '☾杭',
    j: '9',
    weight: 2,
    type: '装備',
    area: '片手',
    specialty: '《刺す》《跳ぶ》',
    target: '単体',
    trait: '武器、白兵',
    effect:
      '攻撃力2。先攻の場合、攻撃力+2。命中判定の達成値+2。くい。突き刺す武器。',
  },
  {
    name: '☾シャベル',
    j: '12',
    weight: 4,
    type: '装備',
    area: '両手',
    specialty: '《殴る》',
    target: '単体',
    trait: '武器、白兵、判定強化',
    effect:
      '攻撃力4。《罠》が指定特技の判定の達成値にプラス1の修正がつく。自身の体力が1以下の時、攻撃力+3。',
  },

  {
    name: '☾銀の首飾り',
    j: 5,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '＜フィールド＞に入った時に【体力】と【気力』が6点増加する。',
  },
  {
    name: '☾ゴーグル',
    j: 10,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: 'アビリティ強化',
    effect:
      'ハンターの【アビリティ】を使用する直前に、追加で1点の気力を払うことができる。そうした場合、達成値にプラス3の修正がつく。',
  },
  {
    name: '☾モノクル',
    j: 10,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《見つける》が指定特技の判定にプラス3の修正がつく。',
  },
  {
    name: '☾浄化の聖印',
    j: 15,
    weight: 1,
    type: '装備',
    area: '頭部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect:
      'アビリティ【腐敗】【悪臭】を無効化する。さらに、それらのアビリティを持つ相手に与えるダメージをプラス5する。',
  },

  {
    name: '☾ポケットジャケット',
    j: 12,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'ポケットのたくさんついたジャケット。所持限界プラス9',
  },
  {
    name: '☾風見鶏のスカーフ',
    j: 20,
    weight: 1,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '先制判定の達成値にプラス2の修正がつく。',
  },
  {
    name: '☾サバイバルベスト',
    j: 15,
    weight: 2,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '【生命力】をプラス3する。',
  },
  {
    name: '☾快適な下着',
    j: 10,
    weight: 1,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: '【精神力】をプラス5する。',
  },
  {
    name: '☾もふもふコート',
    j: 10,
    weight: 4,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect:
      '環境効果『極寒』の影響を受けない。炎や氷のダメージを2点軽減する。『炎上』無効化。',
  },
  {
    name: '☾トラップツール',
    j: 15,
    weight: 4,
    type: '装備',
    area: '胴部',
    specialty: '-',
    target: '自身',
    trait: 'アビリティ強化、判定強化',
    effect:
      'ハンターの【影牢】のダメージ量を[対象が受けている変調×3]点に変更する。《罠》が指定特技の判定にプラス2の修正がつく。',
  },

  {
    name: '☾パワーグラブ',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《掴む》が指定特技の判定にプラス3の修正がつく。',
  },
  {
    name: '☾投手の手袋',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《投げる》が指定特技の判定にプラス3の修正がつく。',
  },
  {
    name: '☾ロンググローブ',
    j: 10,
    weight: 1,
    type: '装備',
    area: '腕部',
    specialty: '-',
    target: '自身',
    trait: '',
    effect: 'アビリティ【冷気】の影響を受けない。ダメージを1点軽減する。',
  },

  {
    name: '☾水かき',
    j: 5,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '水中で行う《泳ぐ》が指定特技の判定にプラス4の修正がつく。',
  },
  {
    name: '☾俊足スニーカー',
    j: 15,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect:
      '《走る》が指定特技の判定にプラス3の修正がつく。探索フェイズ時、障害の突破判定でスペシャルを出すと、行動済にならず続けて行動できる。突破判定にプラス1の修正がつく。',
  },
  {
    name: '☾フィットシューズ',
    j: 20,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect:
      '《バランス》が指定特技の判定にプラス3の修正がつく。『瓦礫』などの足場ペナルティ無効。アビリティ【地震】無効。',
  },
  {
    name: '☾忍者の足袋',
    j: 20,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《歩く》《隠れる》が指定特技の判定にプラス3の修正がつく。',
  },
  {
    name: '☾ペガサスの靴',
    j: 30,
    weight: 2,
    type: '装備',
    area: '脚部',
    specialty: '-',
    target: '自身',
    trait: '判定強化',
    effect: '《走る》《跳ぶ》《踏む》が指定特技の判定にプラス3の修正がつく。',
  },
];
